### ISSUE TITLE
Version history of the User by showing the commit messages

### ISSUE THREAD

**Issue by NishantWankhade** [UDAAN-LEAP/leap-pe-tool#288]
It would be better to add a function to let the user know where have they made the changes while using previously. 
This can be achieved by adding the commit messages which contains the book pages number.

**Comment by NishantWankhade** [comment]
Message retrieval is done at commit number :- ba4c19486996993338e48c12b01e21bfbfbec2a2

**Comment by NishantWankhade** [comment]
@saanvibehele Please documentation of this function as well.

**Comment by NishantWankhade** [comment]
Some bug is there , as if you have changed the doc from Udaan content repo , then it has no commits. So while using sync history feature , it was crashing tool. 
Fixed this at commit number :- 0225533d5ebb4026906968fd5f33f23f144cc8ee
Needs to be tested once again.

**Comment by NishantWankhade** [comment]
@saanvibehele Test take latest pull and test it at your end as well.

**Comment by saanvibehele** [comment]
okay will test it

**Comment by saanvibehele** [comment]
@NishantWankhade I tested this bug
The tool still crashes if the repository is not on github. The bug is not fixed. 
Please can you look into it once again

**Comment by NishantWankhade** [comment]
Sure. Lets discuss in a Tech meeting.

**Comment by saanvibehele** [comment]
okay sure
